# Generated by Django 5.2.1 on 2025-05-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
